name: Build
on: [ push, pull_request, merge_group ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   uses: gradle/actions/wrapper-validation@v4
            -   uses: actions/setup-java@v4
                with:
                    java-version: '21'
                    distribution: 'microsoft'
            -   run: chmod +x ./gradlew
            -   run: ./gradlew check build
